#!/usr/bin/env python3
"""
bin2c.py - Convert binary file to C array
"""

import sys
import os

def bin2c(input_file, output_file, array_name):
    """Convert binary file to C array"""

    # Read binary file
    with open(input_file, 'rb') as f:
        data = f.read()

    # Create output file
    with open(output_file, 'w') as f:
        # Write header
        basename = os.path.basename(input_file)
        f.write(f'/**\n')
        f.write(f' * @file {os.path.basename(output_file)}\n')
        f.write(f' * @brief {basename} - Binary firmware converted to C array\n')
        f.write(f' *\n')
        f.write(f' * Auto-generated by bin2c.py\n')
        f.write(f' */\n\n')
        f.write(f'#include "types.h"\n\n')

        # Write array
        f.write(f'// {basename} binary data\n')
        f.write(f'static const uint8_t {array_name}[] = {{\n')

        # Write data as hex bytes (12 per line)
        for i in range(0, len(data), 12):
            chunk = data[i:i+12]
            hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
            f.write(f'    {hex_bytes},')
            if i + 12 < len(data):
                f.write('\n')

        f.write('\n};\n\n')

        # Write size macros
        f.write(f'#define {array_name.upper()}_SIZE (sizeof({array_name}))\n\n')

        # Write export functions
        f.write(f'// Export firmware data interface\n')
        f.write(f'const uint8_t* {array_name.replace("_fw", "_get_fw_data")}(void) {{\n')
        f.write(f'    return {array_name};\n')
        f.write(f'}}\n\n')
        f.write(f'uint32_t {array_name.replace("_fw", "_get_fw_size")}(void) {{\n')
        f.write(f'    return {array_name.upper()}_SIZE;\n')
        f.write(f'}}\n')

    print(f'Converted {input_file} -> {output_file}')
    print(f'Size: {len(data)} bytes')

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print(f'Usage: {sys.argv[0]} <input.bin> <output.c> <array_name>')
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]
    array_name = sys.argv[3]

    bin2c(input_file, output_file, array_name)
