#!/usr/bin/env python3
"""
bin2c.py - Convert binary file to kernel-safe C firmware array
"""

import sys
import os

def bin2c(input_file, output_file, array_name):
    with open(input_file, 'rb') as f:
        data = f.read()

    base = os.path.basename(input_file)

    with open(output_file, 'w') as f:
        # File header
        f.write("/**\n")
        f.write(f" * @file {os.path.basename(output_file)}\n")
        f.write(f" * @brief {base} - auto-generated firmware binary\n")
        f.write(" *\n")
        f.write(" * Generated by bin2c.py (kernel-safe version)\n")
        f.write(" */\n\n")

        f.write("#include \"types.h\"\n\n")

        # Firmware array
        f.write("// Firmware binary data (page-aligned, read-only)\n")
        f.write("__attribute__((aligned(4096)))\n")
        f.write(f"const uint8_t {array_name}[] = {{\n")

        # Hex dump (12 bytes per line)
        for i in range(0, len(data), 12):
            chunk = data[i:i + 12]
            line = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {line},\n")

        f.write("};\n\n")

        # Size symbol (real symbol, not macro)
        f.write("// Firmware size (bytes)\n")
        f.write(f"const uint32_t {array_name}_size = {len(data)};\n\n")

    print(f"[bin2c] {input_file} -> {output_file}")
    print(f"[bin2c] firmware size: {len(data)} bytes")

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <input.bin> <output.c> <array_name>")
        sys.exit(1)

    bin2c(sys.argv[1], sys.argv[2], sys.argv[3])
