/**
 * @file gen_asm_offsets.c
 * @brief 自动生成 task_t 结构体的汇编偏移量常量
 *
 * 编译运行方式：
 *   gcc -m32 -o gen_asm_offsets gen_asm_offsets.c -I./include
 *   ./gen_asm_offsets > task_offsets.s
 *
 * 然后在 task_impl.s 中包含：
 *   #include "task_offsets.s"
 */

#include <stddef.h>
#include <stdbool.h>

// 不使用 stdio.h，避免与系统的 stdarg.h 冲突

// 手动定义需要的类型（避免依赖 stdint.h）
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
typedef unsigned char uint8_t;

// 包含真实的类型定义（与 types.h 和 task.h 一致）
typedef uint32_t pid_t;
typedef uint32_t uid_t;
typedef uint32_t gid_t;
typedef uint8_t cpu_id_t;
typedef uint32_t time_t;  // ⚠️ 修复：time_t 是 uint32_t，不是 uint64_t！

#define OFFSETOF(type, member) ((unsigned long)&((type *)0)->member)

// 前向声明
struct task_t;
struct trapframe;

// 回调函数类型
typedef bool (*activity_callback_t)(struct task_t* task, void* opaque);
typedef void (*sighandler_t)(int);
typedef void (*task_idle_timer_t)(void);

// 链表头
struct llist_header {
    struct llist_header *next;
    struct llist_header *prev;
};

// 睡眠结构
struct haybed {
    struct llist_header sleepers;
    time_t wakeup_time;
    time_t alarm_time;
};

// 内存管理结构
struct task_mm {
    uint32_t vmroot;
    uint32_t vm_mnt;
    struct task_t* task;
    struct task_mm* guest_mm;
};

// 陷阱帧（部分定义，只需要知道它是指针）
struct trapframe {
    uint32_t regs[20];
};

// 完整的 task_t 定义（必须与 task.h 完全一致！）
struct task_t {
    uint32_t                esp;
    uint32_t                esp0;
    bool                    has_signal;
    uint32_t                *cr3;
    uint32_t                *user_stack;
    uint32_t                signal_handler;
    int                     idle_flags;
    pid_t                   pid;
    pid_t                   ppid;
    uid_t                   uid;
    gid_t                   gid;
    int                     state;
    int                     has_run_user;
    int                     nice;
    time_t                  start_time;
    pid_t                   waitpid;
    cpu_id_t                cpu;
    const char*             directory;
    const char*             name;
    uint32_t                size;
    const char*             csd;
    int                     load_weight;
    uint32_t                entry;
    uint32_t                time_slice;
    uint64_t                vruntime;
    struct llist_header *sched_node;
    struct haybed sleep;
    struct task_mm* mm;
    struct task_t* prev;
    struct task_t* next;
    activity_callback_t check_idle;
    void* idle_context;
    sighandler_t sig_handler;
    uint32_t signal_mask;
    uint32_t pending_signals;
    struct trapframe *tf;
    uint32_t task_total_count;
    uint32_t *pde;
    uint32_t *kstack;
    uint32_t iret_frame[5];
};

// 内联汇编实现 write 系统调用
static void my_write(const char* s) {
    size_t len = 0;
    const char* p = s;
    while (*p++) len++;

    // Linux x86 write syscall: eax=4, ebx=fd, ecx=buf, edx=count
    __asm__ volatile(
        "int $0x80"
        :
        : "a"(4), "b"(1), "c"(s), "d"(len)
    );
}

// 输出数字
static void print_ulong(unsigned long val) {
    char buf[32];
    int i = sizeof(buf) - 1;
    buf[i] = '\n';

    if (val == 0) {
        buf[--i] = '0';
    } else {
        while (val > 0) {
            buf[--i] = '0' + (val % 10);
            val /= 10;
        }
    }

    __asm__ volatile(
        "int $0x80"
        :
        : "a"(4), "b"(1), "c"(&buf[i]), "d"(sizeof(buf) - i)
    );
}

int main(void) {
    // 输出文件头注释
    my_write("/*\n");
    my_write(" * DO NOT EDIT THIS FILE!\n");
    my_write(" * This file is auto-generated by gen_asm_offsets.c\n");
    my_write(" * Run: make gen-offsets\n");
    my_write(" */\n\n");
    my_write("# 32位任务结构体偏移量 (auto-generated)\n");

    // 辅助宏：输出偏移量
    #define PRINT_OFFSET(name, value) \
        my_write(".set TASK_" #name ", "); \
        print_ulong(value);

    // 输出各个字段的偏移量
    PRINT_OFFSET(ESP,         OFFSETOF(struct task_t, esp));
    PRINT_OFFSET(ESP0,        OFFSETOF(struct task_t, esp0));
    PRINT_OFFSET(HAS_SIGNAL,  OFFSETOF(struct task_t, has_signal));
    PRINT_OFFSET(CR3,         OFFSETOF(struct task_t, cr3));
    PRINT_OFFSET(USP,         OFFSETOF(struct task_t, user_stack));
    PRINT_OFFSET(SIG_HANDLER, OFFSETOF(struct task_t, signal_handler));
    PRINT_OFFSET(IDLE_FLAGS,  OFFSETOF(struct task_t, idle_flags));
    PRINT_OFFSET(PID,         OFFSETOF(struct task_t, pid));
    PRINT_OFFSET(PPID,        OFFSETOF(struct task_t, ppid));
    PRINT_OFFSET(UID,         OFFSETOF(struct task_t, uid));
    PRINT_OFFSET(GID,         OFFSETOF(struct task_t, gid));
    PRINT_OFFSET(STATE,       OFFSETOF(struct task_t, state));
    PRINT_OFFSET(HAS_RUN_USER, OFFSETOF(struct task_t, has_run_user));
    PRINT_OFFSET(NICE,        OFFSETOF(struct task_t, nice));
    PRINT_OFFSET(VRUNTIME,    OFFSETOF(struct task_t, vruntime));
    PRINT_OFFSET(SCHED_NODE,  OFFSETOF(struct task_t, sched_node));
    PRINT_OFFSET(MM,          OFFSETOF(struct task_t, mm));
    PRINT_OFFSET(PREV,        OFFSETOF(struct task_t, prev));
    PRINT_OFFSET(NEXT,        OFFSETOF(struct task_t, next));
    PRINT_OFFSET(CHECK_IDLE,  OFFSETOF(struct task_t, check_idle));
    PRINT_OFFSET(IDLE_CONTEXT, OFFSETOF(struct task_t, idle_context));

    // sig_handler 需要不同的名字
    my_write(".set TASK_SIG_HANDLER_FUNC, ");
    print_ulong(OFFSETOF(struct task_t, sig_handler));

    PRINT_OFFSET(SIGNAL_MASK, OFFSETOF(struct task_t, signal_mask));
    PRINT_OFFSET(PENDING_SIGNALS, OFFSETOF(struct task_t, pending_signals));
    PRINT_OFFSET(IFRAME,      OFFSETOF(struct task_t, tf));
    PRINT_OFFSET(TOTAL_COUNT, OFFSETOF(struct task_t, task_total_count));
    PRINT_OFFSET(PDE,         OFFSETOF(struct task_t, pde));
    PRINT_OFFSET(KSTACK,      OFFSETOF(struct task_t, kstack));
    PRINT_OFFSET(IRET_FRAME,  OFFSETOF(struct task_t, iret_frame));

    // 输出结构体总大小
    my_write("\n# Structure size info\n");
    my_write(".set TASK_T_SIZE, ");
    print_ulong(sizeof(struct task_t));

    return 0;
}
