/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by gen_asm_offsets.c
 * Run: make gen-offsets
 */

# 32位任务结构体偏移量 (auto-generated)
.set TASK_ESP, 0
.set TASK_ESP0, 4
.set TASK_HAS_SIGNAL, 8
.set TASK_CR3, 12
.set TASK_USP, 16
.set TASK_SIG_HANDLER, 20
.set TASK_IDLE_FLAGS, 24
.set TASK_PID, 28
.set TASK_PPID, 32
.set TASK_UID, 36
.set TASK_GID, 40
.set TASK_STATE, 44
.set TASK_HAS_RUN_USER, 48
.set TASK_NICE, 52
.set TASK_VRUNTIME, 96
.set TASK_SCHED_NODE, 104
.set TASK_MM, 124
.set TASK_PREV, 128
.set TASK_NEXT, 132
.set TASK_CHECK_IDLE, 136
.set TASK_IDLE_CONTEXT, 140
.set TASK_SIG_HANDLER_FUNC, 144
.set TASK_SIGNAL_MASK, 148
.set TASK_PENDING_SIGNALS, 152
.set TASK_IFRAME, 156
.set TASK_TOTAL_COUNT, 160
.set TASK_PDE, 164
.set TASK_KSTACK, 168
.set TASK_IRET_FRAME, 172

# Structure size info
.set TASK_T_SIZE, 192
